#!/bin/sh
stash=`git stash`
./gradlew clean build
CMD=$?

if ["$stash"x != "No local changes to save"x]
    then
        git stash pop
    else
        echo "No stash, needn't stash pop"
fi

if [$CMD -eq 0]
    then
        echo "Build successfully, continue commit"
        exit 0
    else
        echo "Build failure, stop commit, please fix the problems"
        exit 1
fi